name: test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - uses: ./
        with:
          private-ssh-keys: ${{ secrets.TEST_PRIVATE_REPOSITORY_DEPLOY_KEY }}
      - run: npm install git+ssh://git@github.com/guardian/test-private-repository.git
